X = input("Enter the name of the customer nº1 : ")
A = float(input("Give the price of the item :"))
B = A + A * (0.15 - 0.02)
Y = input("Enter the name of the customer nº2 : ")
A = float(input("Give the price of the item :"))
C = A + A * (0.15 - 0.02)
Z = input("Enter the name of the customer nº3 : ")
A = float (input("Give the price of the item :"))
D = A + A * (0.15 - 0.02)
print("The Total to be paid for the customer",X,":", B , "MAD")
print("The Total to be paid for the customer",Y,":",C, "MAD")
print("The Total to be paid for the customer",Z,":",D,"MAD")  